// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFG0INdsZDfofoFMWQ0-x2wvEylbqdhIw',
    appId: '1:74062662754:web:69f713d36a7d606c5c153b',
    messagingSenderId: '74062662754',
    projectId: 'trashtrack-test',
    authDomain: 'trashtrack-test.firebaseapp.com',
    storageBucket: 'trashtrack-test.appspot.com',
    measurementId: 'G-EJR10HWTSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK6SHRMuppX8uOGhxC-tDnJSov3U0X2vI',
    appId: '1:74062662754:android:715d556c124b2da35c153b',
    messagingSenderId: '74062662754',
    projectId: 'trashtrack-test',
    storageBucket: 'trashtrack-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHEkRpkl69JDWdZXmsoFvNzfMtmOnZwEM',
    appId: '1:74062662754:ios:ce016db35b3062d95c153b',
    messagingSenderId: '74062662754',
    projectId: 'trashtrack-test',
    storageBucket: 'trashtrack-test.appspot.com',
    iosBundleId: 'com.example.trashtrack',
  );
}
